# -*- coding: utf-8 -*-
from __future__ import annotations

SESSION_METADATA_SOURCE_KIND_KEY = "source_kind"
SESSION_METADATA_SOURCE_PROVIDER_KEY = "source_provider"
SESSION_METADATA_SOURCE_LABEL_KEY = "source_label"
SESSION_METADATA_SOURCE_ICON_KEY = "source_icon"
SESSION_METADATA_TITLE_SOURCE_KEY = "title_source"

SESSION_SOURCE_KIND_IM = "im"
SESSION_SOURCE_ICON_IM = "im"
SESSION_TITLE_SOURCE_AUTO = "auto"
SESSION_TITLE_SOURCE_MANUAL = "manual"

__all__ = [
    "SESSION_METADATA_SOURCE_ICON_KEY",
    "SESSION_METADATA_SOURCE_KIND_KEY",
    "SESSION_METADATA_SOURCE_LABEL_KEY",
    "SESSION_METADATA_SOURCE_PROVIDER_KEY",
    "SESSION_METADATA_TITLE_SOURCE_KEY",
    "SESSION_SOURCE_ICON_IM",
    "SESSION_SOURCE_KIND_IM",
    "SESSION_TITLE_SOURCE_AUTO",
    "SESSION_TITLE_SOURCE_MANUAL",
]
